### PR TITLE
A few modifications

### PR DESCRIPTION
**Pull request by echo000**
- h & i seem to signed values (root bone is -1) so read these as signed values not unsigned
- Added Mesh, Material and Bones
- Add a check for Header.NodeHash and set the Nodes hash to this value if it exists
- Add loading from a stream

### CODE REVIEW

**Comment by dtzxporter** [comment]
I've just merged the basis of these changes with tweaks in master. All property values are unsigned by default and are casted in the getters, `i` is also used for face indices, etc.

There is now a getter for the parent index, which properly resolves.

Node.Hash is actually valid being 0, it's fine to even just count from 0-intmax as long as every node has a unique hash or (uuid).

Added overload for the stream load/save.

**Comment by echo000** [comment]
All the new changes look great, one suggestion in regards to this though:
> Node.Hash is actually valid being 0, it's fine to even just count from 0-intmax as long as every node has a unique hash or (uuid).

As it currently stands, this does not appear to load a Hash for a Node when loading from a cast file.
I suggested the `Node.Hash = Header.NodeHash` as this would correctly assign the hash for the node if there is one.

**Comment by dtzxporter** [comment]
Oh duh, I completely missed the fact it wasn't copied over lol

**Comment by dtzxporter** [comment]
> Oh duh, I completely missed the fact it wasn't copied over lol

Now fixed.

**Pull request closed without merging**
